routes/dashboard.php
<div class="gbc-block">

   <b>Enable/Disable NightMode</b>
    <hr>
    <p>NightMode is <span class="c-status"><?=($app_settings->app_status=='0') ? 'disabled' :'enabled'?></span> on your store currently.</p>
    <label for="enable-app"><input id="enable-app" <?php echo ($app_settings->app_status=="1") ? 'checked':''?> class="app-ed-setting" type="radio" name="setting" value="1"> Enable</label>
    
    <label for="disable-app"><input id="disable-app" <?php echo ($app_settings->app_status=="0") ? 'checked':''?> class="app-ed-setting" type="radio" name ="setting" value="0"> Disable</label>
    <button style="float:right;min-width:100px" id="save-settings" class="pcc-btn">Save</button>
    <div>Note : After Enable/Disable app, Store page reload is required to reflect the changes.</div>
</div>


<!-- <div class="gbc-block">



    <form method="post" action="<?=SITE_URL?>/setting.php" id="save_nm_settings" enctype="multipart/form-data">

        <h2>App settings</h2>
            <input type="hidden" name="store_domain" value="<?= $store ?>"> 

            <input type="hidden" name="ac" value="update_setting"> 

            <label>Include Pages</label><br>                               


            <input type="checkbox"  name="homepage" value="Homepage" <?php// if($app_settings->include_pages->homepage == 1) echo "checked";  ?> >
            <label for="vehicle1">Homepage</label><br>


            <input type="checkbox"  name="collection" value="Collection" <?php //if($app_settings->include_pages->collection == 1) echo "checked";  ?>>
            <label for="vehicle2">Collection Page</label><br>


            <input type="checkbox"  name="product" value="Products" <?php// if($app_settings->include_pages->products == 1) echo "checked";  ?>>
            <label for="vehicle3">Products</label><br><br>


            





        <?php //if ( $app_charge_status == '0'){ ?>
           


        <?php //}else{?>


                <label>App logo</label><br>
                <img id="logo_img" src="<?=($app_settings->logo) ?>">

                <input type="file" name="image" accept="image/x-png,image/jpeg" onchange="loadFile(event,'logo_img')" />    <br> <br><br>  


                 <label>Please select button position:</label><br>

                <input required type="radio" name="botton_position" value="top_right" <?php //if($app_settings->button_position == "top_right") echo "checked";  ?> >
                <label for="male">Top Right</label><br>

                <input required type="radio" name="botton_position" value="top_left" <?php// if($app_settings->button_position == "top_left") echo "checked";  ?> >
                <label for="female">Top Left</label><br>

                <input required type="radio" name="botton_position" value="bottom_right" <?php// if($app_settings->button_position == "bottom_right") echo "checked";  ?> >
                <label for="other">Bottom Right</label> <br>

                <input required type="radio" name="botton_position" value="bottom_left" <?php //if($app_settings->button_position == "bottom_left") echo "checked";  ?> >
                <label for="other">Bottom Left</label> <br>      
                                  

        <?php// } ?>



        <button id="premium-upgrade" type="submit" name="upgrade" class="btn-primary" >Save settings</button>

    </form>
</div> -->


<!-- <div class="gbc-block">

    <h2>Exclude Elements</h2><br>
    <p>Please provide your site's page link where you want to exclude elements</p><br>
    <input required type="text" name="exclude_elements" class="exclude_elements">
    <button class="exclude_elm_btn">Proceed</button>
</div> -->

<div class="gbc-block">
    <div class="row">
        <div class="col-12">
            <b>How to use</b>
            <hr>
            1.) Install the NightMode app. <b style="color:#91c516">You Already Did That!</b><br>
            2.) Now enable the app from above & its <b>Done</b><br>
            3.) Right bottom of the Site screen a button will be there to enable or disable Nightmode.<br>
        </div>
    </div>
</div>

<div class="gbc-block">
    <p><b>Feedbacks are most welcome</b></p>
    <hr>
    <textarea maxlength="1000" style="resize:none;margin-bottom: 20px;" class="form-control" name="feedback" id="" cols="30" rows="2" placeholder="Please send us your valuable feedbacks, Or any suggestions you have for improvements."></textarea>
    <p style="font-size: 12px;margin: 0;font-weight: 600;color: #9e9fa0;">Limit 1000 characters</p>
    <button style="float:right;min-width:100px" class="pcc-btn" id="send-feedback">Send</button>
</div>


<div class="gbc-block">
    <div class="row">
        <div class="col-12">
            

            <!-- <p>Like our service? Leave us a positive review!</p> -->
            <!-- 
            <p><i style="color: #91c516" class="fa fa-gift" aria-hidden="true"></i> Get one month free by leaving us a review!</p>
           
            <p style="margin-bottom: 0">Positive feedback keeps us going! Help by leaving a review on Shopify App Store now!. <a href="https://apps.shopify.com/nightmode#reviews" target="_blank">Click here</a> to leave a review.</p>-->
            
        </div>
    </div>
</div>

routes/web.php
<?php   
        
use Illuminate\Support\Facades\Route;

// use App\Http\Controllers\HomeController; 
//use App\Http\Controllers\Admin\CategoryController;

  
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('auth/social', [App\Http\Controllers\Auth\AppLoginController::class, 'show'])->name('social.login');
Route::get('/oauth/{driver}', [App\Http\Controllers\Auth\AppLoginController::class, 'redirectToProvider'])->name('social.oauth');
Route::get('oauth/{driver}/callback', [App\Http\Controllers\Auth\AppLoginController::class, 'handleProviderCallback'])->name('social.callback');

Route::post('/create_link_token', [App\Http\Controllers\Banks::class, 'create_link_token'])->name('createe-token');
Route::post('/exchange_public_token', [App\Http\Controllers\Banks::class, 'exchange_public_token'])->name('exchange-token');
Route::post('/process_plaid_token', [App\Http\Controllers\Banks::class, 'process_plaid_token'])->name('process-token');
Route::post('/create_link_token_v1', [App\Http\Controllers\Banks::class, 'create_link_token_v1'])->name('process-token-v1');
Route::post('/get_balance', [App\Http\Controllers\Banks::class, 'get_balance'])->name('get-balance');



Route::group(['middleware' => 'auth'], function(){

	// Route::get('/', function () {
	//     return view('home');
	// })->name('homeC');

	Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('homeC');
	Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
	Route::get('/banks', [App\Http\Controllers\Banks::class, 'index'])->name('banks');
	Route::get('/transactions', [App\Http\Controllers\TransactionsController::class, 'index'])->name('transactionsController');
	Route::get('/report', [App\Http\Controllers\ReportController::class, 'index'])->name('report');
	Route::get('/personal-information', [App\Http\Controllers\PersonalInformationController::class, 'index'])->name('personalInformationController');
	Route::get('/tax-payment', [App\Http\Controllers\TaxPayment::class, 'index'])->name('taxPayment');
	Route::get('/change-colors', [App\Http\Controllers\ChangeColorsController::class, 'index'])->name('changeColorsController');
	Route::get('/support', [App\Http\Controllers\SupportController::class, 'index'])->name('supportController');
	Route::get('/report-all-categories', [App\Http\Controllers\ReportAllCategoriesController::class, 'index'])->name('reportAllCategoriesController');
	Route::get('/verification-code', [App\Http\Controllers\VerificationCodeController::class, 'index'])->name('verificationCodeController');
	Route::get('/number-verify', [App\Http\Controllers\NumberVerifyController::class, 'index'])->name('numberVerifyController');
	Route::get('/expense', [App\Http\Controllers\ExpenseController::class, 'index'])->name('expenseController');
	Route::get('/income', [App\Http\Controllers\IncomeController::class, 'index'])->name('incomeController');
	Route::get('/transaction-list', [App\Http\Controllers\TransactionList::class, 'index'])->name('transactionList');

	Route::post('/profile-update', [App\Http\Controllers\HomeController::class, 'upload'])->name('profile-update');
	Route::post('/documents-update', [App\Http\Controllers\HomeController::class, 'document_upload'])->name('documents-update');

	Route::get('/change-password', [App\Http\Controllers\ChangePasswordController::class, 'index'])->name('changePasswordController');
	Route::post('/password-update', [App\Http\Controllers\ChangePasswordController::class, 'password_update'])->name('password-update');

	//Route::get('auth/social', 'Auth\AppLoginController@show')->name('social.login');
	//Route::get('oauth/{driver}', 'Auth\AppLoginController@redirectToProvider')->name('social.oauth');
	//Route::get('oauth/{driver}/callback', 'Auth\AppLoginController@handleProviderCallback')->name('social.callback');

	//Route::get('auth/{driver}', 'Auth\GoogleController@redirectToGoogle');
	//Route::get('auth/{driver}/callback', 'Auth\GoogleController@handleGoogleCallback');
 

});


Route::group([
    'prefix'     => 'admin',
    'as'         => 'admin.',
    'namespace'  => 'Admin',
    'middleware' => ['auth', 'App\Http\Middleware\IsAdminMiddleware']
], function () {

    // Route::get('/dashboard', 'HomeController@admin_index')->name('dashboard');
	Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'admin_index'])->name('dashboard');
	Route::get('/users', [App\Http\Controllers\Admin\UsersController::class, 'index'])->name('users');
	Route::get('/banks', [App\Http\Controllers\Admin\BanksController::class, 'index'])->name('banks');
	Route::get('/transaction', [App\Http\Controllers\Admin\TransactionController::class, 'index'])->name('transaction');
	Route::get('/reports', [App\Http\Controllers\Admin\ReportsController::class, 'index'])->name('reports');
	//Route::get('/categories', [App\Http\Controllers\Admin\CategoriesController::class, 'index'])->name('categories');
	//Route::post('/add-categories', [App\Http\Controllers\Admin\CategoriesController::class, 'add_categories'])->name('add-categories');



    Route::resource('categories', CategoryController::class);

    // // Roles
    // Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    // Route::resource('roles', 'RolesController');


});

resources/views/admin/categories.blade.php
@extends('layouts.appAdmin')
  
@section('content') 

@section('title', 'Categories')  
      
   <div class="container-fluid">
      <div class="row">

         @include('layouts.headerAdmin')
      
         <div class="right-main">
           <div class="right-main-inn workout-plan">
              <div class="dashboard-top-div">
                 <div class="dashboard-right-top-div">

                    <div class="search-div">
                      <form action="{{ route('admin.categories.index') }}" method="GET" autocomplete="off">
                          <input type="text" class="input-control search-input" placeholder="Search" name="search">
                          <button type="submit" class="btn btn-default-sm"><i class="fa fa-search" aria-hidden="true"></i></button>
                      </form>
                    </div>
                    
                    <a href="#" class="btn filter" data-toggle="modal" data-target="#create-category">+ Add Category</a>

                 </div>
              </div>             

              <div class="dashboard-main-div posting-page">
                 <div class="dashbord-main-inner">
                    <div class="content-fullpage mCustomScrollbar">
                       <div class="table-responsive">


                           @if ($message = Session::get('success'))
                              <div class="alert alert-success">
                                 <p>{{ $message }}</p>
                              </div>
                           @endif

                           @if ($message = Session::get('warning'))
                              <div class="alert alert-warning">
                                 <p>{{ $message }}</p>
                              </div>
                           @endif


                           @if ($errors->any())
                               <div class="alert alert-danger">
                                   <strong>Whoops!</strong> There were some problems with your input.<br><br>
                                   <ul>
                                       @foreach ($errors->all() as $error)
                                           <li>{{ $error }}</li>
                                       @endforeach
                                   </ul>
                               </div>
                           @endif
 
                           <table class="table table-main">
                              <thead>
                                 <tr>
                                    <th scope="col">Image</th>
                                    <th scope="col">Category Name</th>
                                 </tr>
                              </thead>
                              <tbody>

                                 <?php if(sizeof($categories) > 0) { ?>

                                    @foreach ($categories as $category)
                                       <tr>
                                          <td>
                                            <div class="video-div"><img src="{{asset($category->image)}}"></div>
                                          </td>
                                          <td>{{ $category->title }}</td>
                                          <td>

                                             <form action="{{ route('admin.categories.destroy', $category->id) }}" method="POST">

                                                <!-- <a href="Meal-detail.html" class="edit view"><img src="images/view.png"></a> -->
                                                <a href="{{ route('admin.categories.edit',$category->id) }}" class="edit"><img src="{{ asset('images/admin/edit-icon.png') }}"></a>


                                                @csrf

                                                @method('DELETE')


                                                <!-- <a href="#" class="edit trash" data-toggle="modal" data-target="#delete-user"><img src="{{ asset('images/admin/trash-icon.png') }}"></a> -->

                                                <input type="hidden" name="id" value="{{ $category->id }}">
                                                <button type="submit" class="btn btn-danger">Delete</button>

                                             </form>
                                          </td>
                                       </tr>
                                    @endforeach
                                 <?php } else { ?>

                                    <tr>

                                      <td>  No Categories Yet.</td>
                                    </tr>

                                 <?php  } ?>
                                
                              </tbody>
                           </table>

                           <div class="d-flex justify-content-center">
                              {!! $categories->links() !!}
                          </div>


                       </div>
                    </div>
                 </div>                 
              </div>
           </div>
         </div>
      </div>
   </div>

   <div id="create-category" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="createCategory" aria-hidden="true">
      <div class="modal-dialog">
         <div class="modal-content">
            <div class="modal-header">
               <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;  </button>
               <h4 class="modal-title" id="createCategory">Create Category</h4>
            </div>

            <form action="{{ route('admin.categories.store') }}" method="POST" enctype="multipart/form-data" autocomplete="off">

               @csrf

               <div class="modal-body">

                  <div class="user_image_circle">                        
                     <div class="file-input flex items-center">                            
                        <div class="h-12 w-12 rounded-full overflow-hidden bg-gray-100">                           
                                        
                           <div x-show="previewPhoto" class="h-12 w-12 rounded-full overflow-hidden">                              
                              <img :src="" id="user_p_img" class="h-12 w-12 object-cover" height="50" width="50">                                 
                           </div>
                        </div>
                        <div class="flex items-center edit icon">                            
                           <div class="ml-5 rounded-md shadow-sm">                            
                              <input type="file" 
                                     accept="image/*,capture=camera" 
                                     name="image" id="photo" 
                                     class="custom">
                              <label for="photo" class="edit-image">
                                 <img src="{{ asset('images/edit.png') }}">
                              </label>
                           </div>
                        </div>
                     </div>
                  </div>

                  <div class="form-group firstname">
                     <label class="control-label" for="firstname">Category Name</label>
                     <input type="text" class="form-control" id="catname" name="title" value="" required />
                  </div>              
                 
               </div>
               <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  <button type="submit" class="btn btn-primary">Add Category</button>
               </div>
            </form>
         </div>
      </div>
   </div>

@endsection

@section('scripts')  
   
     
   <script type="text/javascript">

      photo.onchange = evt => {
         const [file] = photo.files
         if (file) {
            user_p_img.src = URL.createObjectURL(file)
         }
      }
     
       
   </script>
@endsection

resources/views/admin/category-edit.blade.php
@extends('layouts.appAdmin')
  
@section('content') 
 
@section('title', 'Categories')  
      
   <div class="container-fluid">
      <div class="row">

         @include('layouts.headerAdmin')
      
         <div class="right-main">
           <div class="right-main-inn workout-plan">
                        

              <div class="dashboard-main-div posting-page">
                 <div class="dashbord-main-inner">
                    <div class="content-fullpage mCustomScrollbar">
                       <div class="table-responsive">

                           <h4>Edit Category</h4>


                           @if ($message = Session::get('success'))
                              <div class="alert alert-success">
                                 <p>{{ $message }}</p>
                              </div>
                           @endif

                           @if ($message = Session::get('warning'))
                              <div class="alert alert-warning">
                                 <p>{{ $message }}</p>
                              </div>
                           @endif


                           @if ($errors->any())
                               <div class="alert alert-danger">
                                   <strong>Whoops!</strong> There were some problems with your input.<br><br>
                                   <ul>
                                       @foreach ($errors->all() as $error)
                                           <li>{{ $error }}</li>
                                       @endforeach
                                   </ul>
                               </div>
                           @endif



                           <form action="{{ route('admin.categories.update', $category[0]->id ) }}" method="POST" enctype="multipart/form-data" autocomplete="off">

                              @csrf                          
                              @method('PUT')

                              <div class="user_image_circle">                        
                                 <div class="file-input flex items-center">                            
                                    <div class="h-12 w-12 rounded-full overflow-hidden bg-gray-100">                           
                                                    
                                       <div x-show="previewPhoto" class="h-12 w-12 rounded-full overflow-hidden">                              
                                          <img src="{{asset($category[0]->image)}}" id="user_p_img" class="h-12 w-12 object-cover" height="50" width="50">                                 
                                       </div>
                                    </div>
                                    <div class="flex items-center edit icon">                            
                                       <div class="ml-5 rounded-md shadow-sm">                            
                                          <input type="file" 
                                                 accept="image/*,capture=camera" 
                                                 name="image" id="photo" 
                                                 class="custom">
                                          <label for="photo" class="edit-image">
                                             <img src="{{ asset('images/edit.png') }}">
                                          </label>
                                       </div>
                                    </div>
                                 </div>
                              </div>

                              <div class="form-group firstname">
                                 <label class="control-label" for="firstname">Category Name</label>
                                 <input type="text" class="form-control" id="catname" name="title" value="{{ $category[0]->title }}" required />
                              </div>          
                              <input type="hidden" name="id" value="{{$category[0]->id}}">
                              <button type="submit" class="btn btn-primary">Edit Category</button>
                              
                           </form>                           
                       </div>
                    </div>
                 </div>                 
              </div>
           </div>
         </div>
      </div>
   </div>

@endsection

@section('scripts')  
   
     
   <script type="text/javascript">

      photo.onchange = evt => {
         const [file] = photo.files
         if (file) {
            user_p_img.src = URL.createObjectURL(file)
         }
      }
     
       
   </script>
@endsection

resources/views/admin/users.blade.php
@extends('layouts.appAdmin')
  
@section('content') 

@section('title', 'Users')
    
   <div class="container-fluid">
      <div class="row">

         @include('layouts.headerAdmin')
         
         <div class="right-main">
            <div class="right-main-inn workout-plan">
               <div class="dashboard-top-div">
                  <div class="dashboard-right-top-div">
                     <div class="search-div">
                        <form action="<?=url('admin/users')?>" method="GET" autocomplete="off">
                           <input type="text" class="input-control search-input" placeholder="Search" name="search">
                           <button type="submit" class="btn btn-default-sm"><i class="fa fa-search" aria-hidden="true"></i></button>
                        </form>
                    </div>
                  </div>
                  
               </div>
               
               <div class="dashboard-main-div posting-page">
                  <div class="dashbord-main-inner">
                     <div class="content-fullpage mCustomScrollbar">
                        <div class="table-responsive">
                           <table class="table table-main">
                              <thead>
                                 <tr>
                                    <th scope="col">First Name</th>
                                    <th scope="col">Last Name</th>
                                    <th scope="col">Email</th>
                                    <th scope="col">Phone</th>
                                    <th scope="col">Tax Payer</th>
                                    <th scope="col">Web File</th>
                                    <th scope="col">EIN</th>
                                 </tr>
                              </thead>
                              <tbody>

                                 <?php if( sizeof($users) > 0 ) {?>

                                    @foreach ($users as $user)
                                       <tr>
                                          <td>{{ $user->first_name }}</td>
                                          <td>{{ $user->last_name }}</td>
                                          <td>{{ $user->email }}</td>
                                          <td>{{ $user->phone }}</td>
                                          <td>{{ $user->tax_payer }}</td>
                                          <td>{{ $user->webfile }}</td>
                                          <td>{{ $user->ein }}</td>
                                       </tr>
                                    @endforeach

                                 <?php }else{ ?>

                                    No Users Yet.

                                 <?php } ?>
                                                               
                              </tbody>
                           </table>

                           <div class="d-flex justify-content-center">
                              {!! $users->links() !!}
                           </div>


                        </div>
                     </div>
                  </div>
                  
               </div>
               
            </div>
         </div>
      </div>
   </div>
      
   <div id="delete-user" class="modal fade" role="dialog">
      <div class="modal-dialog">
         <!-- Modal content-->
         <div class="modal-content">
            <div class="modal-header">
               <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
               <div class="modal-body-content">
                  <span class="dlt-img"><img src="images/done.png" alt=""></span>
                  <h4>Done!</h4>
                  <p>Workout Partner deleted successfully</p>
                  <button type="button" class="btn btn-default" data-dismiss="modal">Ok</button>
               </div>
               <!-- modal-body-content -->
            </div>
         </div>
      </div>
   </div>
      
@endsection

@section('scripts')

   <script type="text/javascript">
        
   </script>

@endsection